### ISSUE TITLE
启动服务后欢律app获取不到版本号

### ISSUE THREAD

**Issue by keeno1982** [icyray/encox-downgradeServer#1]
手机小米9，耳机encox，欢律版本1.0.39，降级固件 X19E7_04_A.1.3.2_210313.bin

服务器已正常启动，但是设置代理后，启动欢律APP没有获取到固件版本，无法降级，麻烦看下。
日志如下：
警告：降级操作具有危险性，失败导致设备损坏的风险由您自行承担！
请在手机上设置代理后，使用降级版欢律刷入固件。
检测到未加密固件！
尝试读取固件信息...
固件读取完毕，固件版本号: 132，适用设备 ID: 061410，设备名: OPPO Enco X.
已启动降级代理服务器，端口：8090
192.168.196.65 - - [01/Nov/2021 22:06:24] code 501, message Unsupported method ('CONNECT')
192.168.196.65 - - [01/Nov/2021 22:06:24] "CONNECT data.mistat.xiaomi.com:443 HTTP/1.1" 501 -
192.168.196.65 - - [01/Nov/2021 22:06:25] code 501, message Unsupported method ('CONNECT')
192.168.196.65 - - [01/Nov/2021 22:06:25] "CONNECT data.mistat.xiaomi.com:443 HTTP/1.1" 501 -
192.168.196.65 - - [01/Nov/2021 22:06:26] code 501, message Unsupported method ('CONNECT')
192.168.196.65 - - [01/Nov/2021 22:06:26] "CONNECT data.mistat.xiaomi.com:443 HTTP/1.1" 501 -
192.168.196.65 - - [01/Nov/2021 22:06:36] code 501, message Unsupported method ('CONNECT')
192.168.196.65 - - [01/Nov/2021 22:06:36] "CONNECT obus-cn.dc.heytapmobi.com:443 HTTP/1.1" 501 -
192.168.196.65 - - [01/Nov/2021 22:06:37] code 501, message Unsupported method ('CONNECT')
192.168.196.65 - - [01/Nov/2021 22:06:37] "CONNECT data.mistat.xiaomi.com:443 HTTP/1.1" 501 -
192.168.196.65 - - [01/Nov/2021 22:06:42] code 501, message Unsupported method ('CONNECT')
192.168.196.65 - - [01/Nov/2021 22:06:42] "CONNECT smarthome.iot.oppomobile.com:443 HTTP/1.1" 501 -
192.168.196.65 - - [01/Nov/2021 22:06:43] code 501, message Unsupported method ('CONNECT')
192.168.196.65 - - [01/Nov/2021 22:06:43] "CONNECT appconf.heytapdownload.com:443 HTTP/1.1" 501 -
192.168.196.65 - - [01/Nov/2021 22:06:43] code 501, message Unsupported method ('CONNECT')
192.168.196.65 - - [01/Nov/2021 22:06:43] "CONNECT smarthome.iot.oppomobile.com:443 HTTP/1.1" 501 -
192.168.196.65 - - [01/Nov/2021 22:06:43] code 501, message Unsupported method ('CONNECT')
192.168.196.65 - - [01/Nov/2021 22:06:43] "CONNECT smarthome.iot.oppomobile.com:443 HTTP/1.1" 501 -
192.168.196.65 - - [01/Nov/2021 22:06:44] code 501, message Unsupported method ('CONNECT')
192.168.196.65 - - [01/Nov/2021 22:06:44] "CONNECT api-cn.open.heytapmobi.com:443 HTTP/1.1" 501 -
192.168.196.65 - - [01/Nov/2021 22:06:44] code 501, message Unsupported method ('CONNECT')
192.168.196.65 - - [01/Nov/2021 22:06:44] "CONNECT data.mistat.xiaomi.com:443 HTTP/1.1" 501 -
192.168.196.65 - - [01/Nov/2021 22:06:48] code 501, message Unsupported method ('CONNECT')
192.168.196.65 - - [01/Nov/2021 22:06:48] "CONNECT data.mistat.xiaomi.com:443 HTTP/1.1" 501 -
192.168.196.65 - - [01/Nov/2021 22:07:10] code 501, message Unsupported method ('CONNECT')
192.168.196.65 - - [01/Nov/2021 22:07:10] "CONNECT data.mistat.xiaomi.com:443 HTTP/1.1" 501 -
192.168.196.65 - - [01/Nov/2021 22:08:11] code 501, message Unsupported method ('CONNECT')
192.168.196.65 - - [01/Nov/2021 22:08:11] "CONNECT data.mistat.xiaomi.com:443 HTTP/1.1" 501 -
192.168.196.65 - - [01/Nov/2021 22:08:14] code 501, message Unsupported method ('CONNECT')
192.168.196.65 - - [01/Nov/2021 22:08:14] "CONNECT data.mistat.xiaomi.com:443 HTTP/1.1" 501 -
192.168.196.65 - - [01/Nov/2021 22:08:24] code 501, message Unsupported method ('CONNECT')
192.168.196.65 - - [01/Nov/2021 22:08:24] "CONNECT tracking.miui.com:443 HTTP/1.1" 501 -

**Comment by icyray** [comment]
之前没有说清楚，这个“降级版欢律”是需要手动修改欢律的包实现的。
欢律内部请求使用的是 https ，因此在没有安装证书的情况下是获取不到相关信息的。需要使用 mt 管理器或其他反编译工具，查找字符串`https://smarthome.iot.oppomobile.com/v1/earphone/firmwareInfo`，修改为`http://smarthome.iot.oppomobile.com/v1/earphone/firmwareInfo`，即将`https`改为`http`，并重新打包安装。

**Comment by icyray** [comment]
放个修改好的包好了，https://icyray.lanzoui.com/ii7Z2lrstni

**Comment by keeno1982** [comment]
感谢🙏，我试试

**Comment by keeno1982** [comment]
成功！谢谢！
